export const FEATURES = [
  { key: "dashboard", label: "Dashboard" },
  { key: "conversations", label: "Conversations" },
  { key: "calendars", label: "Calendars" },
  { key: "contacts", label: "Contacts" },
  { key: "opportunities", label: "Opportunities" },
  { key: "payments", label: "Payments" },
  { key: "marketing", label: "Marketing" },
  { key: "email", label: "Email" },
  { key: "automation", label: "Automation" },
  { key: "reputation", label: "Reputation" },
  { key: "blogs", label: "Blogs" },
  { key: "memberships", label: "Memberships" },
  { key: "integration", label: "Integration" },
  { key: "settings", label: "Settings" },
  { key: "funnels-websites", label: "Funnels Websites" },
  { key: "form-builder", label: "Form Builder" },
  { key: "survey-builder", label: "Survey Builder" },
  { key: "66a97ca06e16787562476424", label: "CrocoLive" },
  { key: "5e9efed3-e795-4fe6-8e56-9f9bb6c730fb", label: "CrocoLab" },
  { key: "0bae2e9d-79d4-4513-84e1-a3056dc45acb", label: "CrocoClub" },
  { key: "other", label: "Other" },
];
